spring:
  profiles:
    active: dev


---
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: robot-remote
  redis:
    redisson:
      file: classpath:redission.yaml

server:
  port: 88
  tomcat:
    max-connections: 1000
    connection-timeout: 3000
  servlet:
    context-path: /reminder

logging:
  config: classpath:log4j.properties


---
spring:
  config:
    activate:
      on-profile: prod
