spring:
  profiles:
    active: development


---
spring:
  config:
    activate:
      on-profile: development

  application:
    name: robot-qqrobot

  redis:
    redisson:
      file: classpath:redisson.yaml

  datasource:
    name: robot
    #url: jdbc:mysql://127.0.0.1:3306/robot?characterEncoding=utf-8
    #username: root
    #password: root
    url: jdbc:mysql://192.168.0.30:3306/robot?characterEncoding=utf-8&useSSL=false
    username: root
    password: ULTR999)_+mysql
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  type-aliases-package: cn.ultronxr.qqrobot.bean.mybatis.bean
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8093
  servlet:
    context-path: /qqrobot

logging:
  config: classpath:log4j.properties


---
spring:
  config:
    activate:
      on-profile: main

  application:
    name: robot-qqrobot

  redis:
    redisson:
      file: classpath:redisson.yaml

  datasource:
    name: robot
    url: jdbc:mysql://192.168.0.30:3306/robot?characterEncoding=utf-8&useSSL=false
    username: root
    password: ULTR999)_+mysql
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  type-aliases-package: cn.ultronxr.qqrobot.bean.mybatis.bean
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8093
  servlet:
    context-path: /qqrobot

logging:
  config: classpath:log4j.properties
