# maven打包时添加参数 -P dev/prod
# 应用启动、测试时添加参数 -Dspring.profiles.active=dev/prod
profile: $spring.profiles.active$

spring:
  profiles:
    # 激活的配置（dev/prod）
    active: ${profile}
    # 引入的配置（application-devenv.yml/application-prodenv.yml）
    include:
      - ${profile}env

  application:
    name: robot-qqrobot

  redis:
    redisson:
      file: classpath:conf/redisson.yaml

mybatis:
  type-aliases-package: cn.ultronxr.qqrobot.bean.mybatis.bean
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8093
  servlet:
    context-path: /qqrobot

logging:
  config: classpath:log4j.properties


---
spring:
  config:
    activate:
      on-profile: dev


---
spring:
  config:
    activate:
      on-profile: prod

