spring:
  profiles:
    active: $spring.profiles.active$
    # maven打包时添加参数 -P dev/prod
    # 应用启动时添加参数 -Dspring.profiles.active=dev/prod

  application:
    name: robot-qqrobot

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  type-aliases-package: cn.ultronxr.qqrobot.bean.mybatis.bean
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8093
  servlet:
    context-path: /qqrobot

logging:
  config: classpath:log4j.properties

redisson-env-filename: redisson-$spring.profiles.active$.yaml


---
spring:
  config:
    activate:
      on-profile: dev

  redis:
    redisson:
      file: classpath:redisson-dev.yaml

  datasource:
    name: robot
    url: jdbc:mysql://127.0.0.1:3306/robot?characterEncoding=utf-8&useSSL=false
    username: root
    password: root


---
spring:
  config:
    activate:
      on-profile: prod

  redis:
    redisson:
      file: classpath:redisson-prod.yaml

  datasource:
    name: robot
    url: jdbc:mysql://192.168.0.30:3306/robot?characterEncoding=utf-8&useSSL=false
    username: root
    password: ULTR999)_+mysql
