spring:
  profiles:
    active: development

---
spring:
  profiles: development
  application:
    name: httpserver

server:
  port: 88
  tomcat:
    max-connections: 10000
    connection-timeout: 3000
  servlet:
    context-path: /reminder

---
spring:
  profiles: main
